package Captcha;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */



import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author rober
 */
public class Captcha extends javax.swing.JPanel {

    public Captcha() {
        initComponents();
        lblDone.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicio = new javax.swing.JPanel();
        lblVerify = new javax.swing.JLabel();
        lblDone = new javax.swing.JLabel();
        chkVerificar = new javax.swing.JCheckBox();
        panelMotocicletas1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        button10 = new javax.swing.JToggleButton();
        lbl11 = new javax.swing.JLabel();
        button11 = new javax.swing.JToggleButton();
        lbl12 = new javax.swing.JLabel();
        button12 = new javax.swing.JToggleButton();
        lbl13 = new javax.swing.JLabel();
        button13 = new javax.swing.JToggleButton();
        lbl14 = new javax.swing.JLabel();
        button14 = new javax.swing.JToggleButton();
        lbl15 = new javax.swing.JLabel();
        button15 = new javax.swing.JToggleButton();
        lbl16 = new javax.swing.JLabel();
        button16 = new javax.swing.JToggleButton();
        lbl17 = new javax.swing.JLabel();
        button17 = new javax.swing.JToggleButton();
        lbl18 = new javax.swing.JLabel();
        button18 = new javax.swing.JToggleButton();
        btnCambiar1 = new javax.swing.JButton();
        btnVerificar1 = new javax.swing.JButton();
        panelMotocicletas2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        button1 = new javax.swing.JToggleButton();
        lbl2 = new javax.swing.JLabel();
        button2 = new javax.swing.JToggleButton();
        lbl3 = new javax.swing.JLabel();
        button3 = new javax.swing.JToggleButton();
        lbl4 = new javax.swing.JLabel();
        button4 = new javax.swing.JToggleButton();
        lbl5 = new javax.swing.JLabel();
        button5 = new javax.swing.JToggleButton();
        lbl6 = new javax.swing.JLabel();
        button6 = new javax.swing.JToggleButton();
        lbl7 = new javax.swing.JLabel();
        button7 = new javax.swing.JToggleButton();
        lbl8 = new javax.swing.JLabel();
        button8 = new javax.swing.JToggleButton();
        lbl9 = new javax.swing.JLabel();
        button9 = new javax.swing.JToggleButton();
        btnCambiar = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        panelSemaforo1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl37 = new javax.swing.JLabel();
        button37 = new javax.swing.JToggleButton();
        lbl38 = new javax.swing.JLabel();
        button38 = new javax.swing.JToggleButton();
        lbl39 = new javax.swing.JLabel();
        button39 = new javax.swing.JToggleButton();
        lbl40 = new javax.swing.JLabel();
        button40 = new javax.swing.JToggleButton();
        lbl41 = new javax.swing.JLabel();
        button41 = new javax.swing.JToggleButton();
        lbl42 = new javax.swing.JLabel();
        button42 = new javax.swing.JToggleButton();
        lbl43 = new javax.swing.JLabel();
        button43 = new javax.swing.JToggleButton();
        lbl44 = new javax.swing.JLabel();
        button44 = new javax.swing.JToggleButton();
        lbl45 = new javax.swing.JLabel();
        button45 = new javax.swing.JToggleButton();
        btnCambiar4 = new javax.swing.JButton();
        btnVerificar4 = new javax.swing.JButton();
        panelSemaforo2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl19 = new javax.swing.JLabel();
        button19 = new javax.swing.JToggleButton();
        lbl20 = new javax.swing.JLabel();
        button20 = new javax.swing.JToggleButton();
        lbl21 = new javax.swing.JLabel();
        button21 = new javax.swing.JToggleButton();
        lbl22 = new javax.swing.JLabel();
        button22 = new javax.swing.JToggleButton();
        lbl23 = new javax.swing.JLabel();
        button23 = new javax.swing.JToggleButton();
        lbl24 = new javax.swing.JLabel();
        button24 = new javax.swing.JToggleButton();
        lbl25 = new javax.swing.JLabel();
        button25 = new javax.swing.JToggleButton();
        lbl26 = new javax.swing.JLabel();
        button26 = new javax.swing.JToggleButton();
        lbl27 = new javax.swing.JLabel();
        button27 = new javax.swing.JToggleButton();
        btnCambiar2 = new javax.swing.JButton();
        btnVerificar2 = new javax.swing.JButton();
        panelInformacion = new javax.swing.JPanel();
        pI = new javax.swing.JPanel();
        lbl28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btnAceptar1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        panelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVerify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/captcha.png"))); // NOI18N
        lblVerify.setText("jLabel1");
        panelInicio.add(lblVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 120));

        lblDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/captcha2.png"))); // NOI18N
        panelInicio.add(lblDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 120));

        chkVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVerificarActionPerformed(evt);
            }
        });
        panelInicio.add(chkVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 50, 40));

        add(panelInicio, "card7");

        panelMotocicletas1.setPreferredSize(new java.awt.Dimension(520, 720));
        panelMotocicletas1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("contengan motocicletas");
        panelMotocicletas1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 380, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Selecciona todas las imagenes que");
        panelMotocicletas1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 480, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoazulito.jpg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 147, 255)));
        panelMotocicletas1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 6, 500, 100));

        lbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/sinMoto1.jpg"))); // NOI18N
        lbl10.setText("jLabel4");
        panelMotocicletas1.add(lbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, 140));

        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        panelMotocicletas1.add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 160));

        lbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/NOsemaforo3.png"))); // NOI18N
        lbl11.setText("jLabel4");
        panelMotocicletas1.add(lbl11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, 140));

        button11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button11MouseClicked(evt);
            }
        });
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        panelMotocicletas1.add(button11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 160, 160));

        lbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/moto1.jpg"))); // NOI18N
        lbl12.setText("jLabel4");
        panelMotocicletas1.add(lbl12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 140, 140));

        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });
        panelMotocicletas1.add(button12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 160, 160));

        lbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/semaforo1.jpg"))); // NOI18N
        lbl13.setText("jLabel4");
        panelMotocicletas1.add(lbl13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, 140));

        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });
        panelMotocicletas1.add(button13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, 160));

        lbl14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/moto3.jpg"))); // NOI18N
        lbl14.setText("jLabel4");
        panelMotocicletas1.add(lbl14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 140, 140));

        button14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button14ActionPerformed(evt);
            }
        });
        panelMotocicletas1.add(button14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 160, 160));

        lbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/sinMoto2.png"))); // NOI18N
        lbl15.setText("jLabel4");
        panelMotocicletas1.add(lbl15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 140, 140));

        button15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button15ActionPerformed(evt);
            }
        });
        panelMotocicletas1.add(button15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 160, 160));

        lbl16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/NOsemaforo.jpg"))); // NOI18N
        lbl16.setText("jLabel4");
        panelMotocicletas1.add(lbl16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 140, 140));

        button16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button16ActionPerformed(evt);
            }
        });
        panelMotocicletas1.add(button16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 160, 160));

        lbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/moto4.jpg"))); // NOI18N
        lbl17.setText("jLabel4");
        panelMotocicletas1.add(lbl17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 140, 140));

        button17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button17ActionPerformed(evt);
            }
        });
        panelMotocicletas1.add(button17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 160, 160));

        lbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/moto2.png"))); // NOI18N
        lbl18.setText("jLabel4");
        panelMotocicletas1.add(lbl18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 140, 140));

        button18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button18ActionPerformed(evt);
            }
        });
        panelMotocicletas1.add(button18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 160, 160));

        btnCambiar1.setBackground(java.awt.SystemColor.controlHighlight);
        btnCambiar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/refrescar_1.png"))); // NOI18N
        btnCambiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiar1ActionPerformed(evt);
            }
        });
        panelMotocicletas1.add(btnCambiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 60, 50));

        btnVerificar1.setBackground(new java.awt.Color(0, 153, 255));
        btnVerificar1.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        btnVerificar1.setForeground(new java.awt.Color(255, 255, 255));
        btnVerificar1.setText("VERIFICAR");
        btnVerificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificar1ActionPerformed(evt);
            }
        });
        panelMotocicletas1.add(btnVerificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 650, 130, 50));

        add(panelMotocicletas1, "card2");

        panelMotocicletas2.setPreferredSize(new java.awt.Dimension(520, 720));
        panelMotocicletas2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("contengan motocicletas");
        panelMotocicletas2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 380, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selecciona todas las imagenes que");
        panelMotocicletas2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 480, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoazulito.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 147, 255)));
        panelMotocicletas2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 6, 500, 100));

        lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/moto1.jpg"))); // NOI18N
        panelMotocicletas2.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, 140));

        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelMotocicletas2.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 160));

        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/sinMoto1.jpg"))); // NOI18N
        lbl2.setText("jLabel4");
        panelMotocicletas2.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, 140));

        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
        });
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panelMotocicletas2.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 160, 160));

        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/sinMoto2.png"))); // NOI18N
        lbl3.setText("jLabel4");
        panelMotocicletas2.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 140, 140));

        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        panelMotocicletas2.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 160, 160));

        lbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/sinMoto3.png"))); // NOI18N
        lbl4.setText("jLabel4");
        panelMotocicletas2.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, 140));

        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        panelMotocicletas2.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, 160));

        lbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/sinMoto4.png"))); // NOI18N
        lbl5.setText("jLabel4");
        panelMotocicletas2.add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 140, 140));

        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        panelMotocicletas2.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 160, 160));

        lbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/moto2.png"))); // NOI18N
        lbl6.setText("jLabel4");
        panelMotocicletas2.add(lbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 140, 140));

        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        panelMotocicletas2.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 160, 160));

        lbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/moto4.jpg"))); // NOI18N
        lbl7.setText("jLabel4");
        panelMotocicletas2.add(lbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 140, 140));

        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        panelMotocicletas2.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 160, 160));

        lbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/semaforo1.jpg"))); // NOI18N
        lbl8.setText("jLabel4");
        panelMotocicletas2.add(lbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 140, 140));

        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        panelMotocicletas2.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 160, 160));

        lbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/moto3.jpg"))); // NOI18N
        lbl9.setText("jLabel4");
        panelMotocicletas2.add(lbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 140, 140));

        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        panelMotocicletas2.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 160, 160));

        btnCambiar.setBackground(java.awt.SystemColor.controlHighlight);
        btnCambiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/refrescar_1.png"))); // NOI18N
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        panelMotocicletas2.add(btnCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 60, 50));

        btnVerificar.setBackground(new java.awt.Color(0, 153, 255));
        btnVerificar.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        btnVerificar.setForeground(new java.awt.Color(255, 255, 255));
        btnVerificar.setText("VERIFICAR");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        panelMotocicletas2.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 650, 130, 50));

        add(panelMotocicletas2, "card3");

        jPanel7.setPreferredSize(new java.awt.Dimension(520, 720));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("contengan semaforos");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 380, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Selecciona todas las imagenes que");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 480, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoazulito.jpg"))); // NOI18N
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 147, 255)));
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 6, 500, 100));

        lbl37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/NOsemaforo4.jpg"))); // NOI18N
        lbl37.setText("jLabel4");
        jPanel7.add(lbl37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, 140));

        button37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button37ActionPerformed(evt);
            }
        });
        jPanel7.add(button37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 160));

        lbl38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/semaforo1.jpg"))); // NOI18N
        lbl38.setText("jLabel4");
        jPanel7.add(lbl38, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, 140));

        button38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button38MouseClicked(evt);
            }
        });
        button38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button38ActionPerformed(evt);
            }
        });
        jPanel7.add(button38, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 160, 160));

        lbl39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/moto1.jpg"))); // NOI18N
        lbl39.setText("jLabel4");
        jPanel7.add(lbl39, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 140, 140));

        button39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button39ActionPerformed(evt);
            }
        });
        jPanel7.add(button39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 160, 160));

        lbl40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/semaforo4.jpg"))); // NOI18N
        lbl40.setText("jLabel4");
        jPanel7.add(lbl40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, 140));

        button40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button40ActionPerformed(evt);
            }
        });
        jPanel7.add(button40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, 160));

        lbl41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/NOsemaforo.jpg"))); // NOI18N
        lbl41.setText("jLabel4");
        jPanel7.add(lbl41, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 140, 140));

        button41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button41ActionPerformed(evt);
            }
        });
        jPanel7.add(button41, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 160, 160));

        lbl42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/NOsemaforo3.png"))); // NOI18N
        lbl42.setText("jLabel4");
        jPanel7.add(lbl42, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 140, 140));

        button42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button42ActionPerformed(evt);
            }
        });
        jPanel7.add(button42, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 160, 160));

        lbl43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/semaforo3.jpg"))); // NOI18N
        lbl43.setText("jLabel4");
        jPanel7.add(lbl43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 140, 140));

        button43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button43ActionPerformed(evt);
            }
        });
        jPanel7.add(button43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 160, 160));

        lbl44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/NOsemaforo2.jpg"))); // NOI18N
        lbl44.setText("jLabel4");
        jPanel7.add(lbl44, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 140, 140));

        button44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button44ActionPerformed(evt);
            }
        });
        jPanel7.add(button44, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 160, 160));

        lbl45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/semaforo2.jpg"))); // NOI18N
        lbl45.setText("jLabel4");
        jPanel7.add(lbl45, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 140, 140));

        button45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button45ActionPerformed(evt);
            }
        });
        jPanel7.add(button45, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 160, 160));

        btnCambiar4.setBackground(java.awt.SystemColor.controlHighlight);
        btnCambiar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/refrescar_1.png"))); // NOI18N
        btnCambiar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiar4ActionPerformed(evt);
            }
        });
        jPanel7.add(btnCambiar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 60, 50));

        btnVerificar4.setBackground(new java.awt.Color(0, 153, 255));
        btnVerificar4.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        btnVerificar4.setForeground(new java.awt.Color(255, 255, 255));
        btnVerificar4.setText("VERIFICAR");
        btnVerificar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificar4ActionPerformed(evt);
            }
        });
        jPanel7.add(btnVerificar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 650, 130, 50));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelSemaforo1Layout = new javax.swing.GroupLayout(panelSemaforo1);
        panelSemaforo1.setLayout(panelSemaforo1Layout);
        panelSemaforo1Layout.setHorizontalGroup(
            panelSemaforo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSemaforo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelSemaforo1Layout.setVerticalGroup(
            panelSemaforo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSemaforo1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelSemaforo1, "card6");

        panelSemaforo2.setPreferredSize(new java.awt.Dimension(520, 720));
        panelSemaforo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("contengan semaforos");
        panelSemaforo2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 380, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Selecciona todas las imagenes que");
        panelSemaforo2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 480, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoazulito.jpg"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 147, 255)));
        panelSemaforo2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 6, 500, 100));

        lbl19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/moto3.jpg"))); // NOI18N
        lbl19.setText("jLabel4");
        panelSemaforo2.add(lbl19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, 140));

        button19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button19ActionPerformed(evt);
            }
        });
        panelSemaforo2.add(button19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 160));

        lbl20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/semaforo1.jpg"))); // NOI18N
        lbl20.setText("jLabel4");
        panelSemaforo2.add(lbl20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, 140));

        button20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button20MouseClicked(evt);
            }
        });
        button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button20ActionPerformed(evt);
            }
        });
        panelSemaforo2.add(button20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 160, 160));

        lbl21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/semaforo4.jpg"))); // NOI18N
        lbl21.setText("jLabel4");
        panelSemaforo2.add(lbl21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 140, 140));

        button21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button21ActionPerformed(evt);
            }
        });
        panelSemaforo2.add(button21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 160, 160));

        lbl22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/sinMoto4.png"))); // NOI18N
        lbl22.setText("jLabel4");
        panelSemaforo2.add(lbl22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, 140));

        button22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button22ActionPerformed(evt);
            }
        });
        panelSemaforo2.add(button22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, 160));

        lbl23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/semaforo3.jpg"))); // NOI18N
        lbl23.setText("jLabel4");
        panelSemaforo2.add(lbl23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 140, 140));

        button23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button23ActionPerformed(evt);
            }
        });
        panelSemaforo2.add(button23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 160, 160));

        lbl24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/NOsemaforo4.jpg"))); // NOI18N
        lbl24.setText("jLabel4");
        panelSemaforo2.add(lbl24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 140, 140));

        button24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button24ActionPerformed(evt);
            }
        });
        panelSemaforo2.add(button24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 160, 160));

        lbl25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motos/sinMoto2.png"))); // NOI18N
        lbl25.setText("jLabel4");
        panelSemaforo2.add(lbl25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 140, 140));

        button25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button25ActionPerformed(evt);
            }
        });
        panelSemaforo2.add(button25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 160, 160));

        lbl26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/semaforo2.jpg"))); // NOI18N
        lbl26.setText("jLabel4");
        panelSemaforo2.add(lbl26, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 140, 140));

        button26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button26ActionPerformed(evt);
            }
        });
        panelSemaforo2.add(button26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 160, 160));

        lbl27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semaforos/NOsemaforo3.png"))); // NOI18N
        lbl27.setText("jLabel4");
        panelSemaforo2.add(lbl27, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 140, 140));

        button27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button27ActionPerformed(evt);
            }
        });
        panelSemaforo2.add(button27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 160, 160));

        btnCambiar2.setBackground(java.awt.SystemColor.controlHighlight);
        btnCambiar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/refrescar_1.png"))); // NOI18N
        btnCambiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiar2ActionPerformed(evt);
            }
        });
        panelSemaforo2.add(btnCambiar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 60, 50));

        btnVerificar2.setBackground(new java.awt.Color(0, 153, 255));
        btnVerificar2.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        btnVerificar2.setForeground(new java.awt.Color(255, 255, 255));
        btnVerificar2.setText("VERIFICAR");
        btnVerificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificar2ActionPerformed(evt);
            }
        });
        panelSemaforo2.add(btnVerificar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 650, 130, 50));

        add(panelSemaforo2, "card5");

        panelInformacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/recaptcha.png"))); // NOI18N
        pI.add(lbl28, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jScrollPane2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("¿Qué es un CAPTCHA? es una prueba de seguridad\n que se utiliza para verificar si un usuario es humano\n y no un bot. \n\nCAPTCHA es un acrónimo que significa \"Test de \nTuring completamente automático y público para \ndiferenciar ordenadores de humanos\"\n\n¿Por qué se utiliza un CAPTCHA? ayudan a proteger\n nuestros sistemas de spam y otros tipos de ataques\n automatizados. Al requerir esta verificación \nadicional, podemos asegurarnos de que solo los\nusuarios reales puedan acceder a nuestros \nservicios.\n\n¿Cómo resolver un CAPTCHA? Simplemente \nselecciona todas las imágenes que coincidan con\n la descripción proporcionada. Si tienes dificultades\npuedes hacer clic en el botón 'Recargar' para \nobtener una nueva imagen.\n\n¿Necesitas ayuda? Si tienes alguna pregunta o \nencuentras algún problema, contáctanos a través\nde nuestro formulario de soporte.");
        jScrollPane2.setViewportView(jTextArea2);

        pI.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 310, 430));

        btnAceptar1.setText("Aceptar");
        pI.add(btnAceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, 33));

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        jLabel12.setText("INFORMACION - reCAPTCHA");
        pI.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        panelInformacion.add(pI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 710));

        add(panelInformacion, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked

    }//GEN-LAST:event_button2MouseClicked

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed

    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed

    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed

    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed

    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed

    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed

    }//GEN-LAST:event_button9ActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
       JPanel[] captchas = {panelMotocicletas1, panelSemaforo1, panelSemaforo2};
    JPanel currentPanel = panelMotocicletas2; // Panel inicial
    // Ocultar el panel actual
    currentPanel.setVisible(false);
    // Seleccionar un panel aleatorio diferente al actual
    Random random = new Random();
    JPanel selectedPanel;
    do {
        int randomIndex = random.nextInt(captchas.length);
        selectedPanel = captchas[randomIndex];
    } while (selectedPanel == currentPanel); 
    
    // Actualizar el panel actual y mostrar el nuevo panel seleccionado
    selectedPanel.setVisible(true);
    currentPanel = selectedPanel; // Actualizar el panel actual a este nuevo
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed

        // Identificar los botones correctos
        boolean[] correctSelections = {
            button1.isSelected(),
            button6.isSelected(),
            button7.isSelected(),
            button9.isSelected()
        };

        // Identificar todos los botones seleccionados
        JToggleButton[] allButtons = {
            button1, button2, button3, button4, button5, button6, button7, button8, button9
        };

        // Contar cuántos botones correctos están seleccionados
        int correctCount = 0;
        for (boolean isSelected : correctSelections) {
            if (isSelected) correctCount++;
        }

        // Verificar si exactamente 4 botones correctos están seleccionados y ningún otro
        if (correctCount == 4) {
            boolean onlyCorrectSelected = true;
            for (JToggleButton button : allButtons) {
                if (button.isSelected() && !(button == button1 || button == button6 || button == button7 || button == button9)) {
                    onlyCorrectSelected = false;
                    break;
                }
            }

            if (onlyCorrectSelected) {
                JOptionPane.showMessageDialog(null, "¡Felicidades, no eres un robot!");
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                if (frame != null) {
                    frame.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Vuelve a intentarlo");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vuelve a intentarlo");
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button10ActionPerformed

    private void button11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button11MouseClicked

    }//GEN-LAST:event_button11MouseClicked

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed

    }//GEN-LAST:event_button11ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed

    }//GEN-LAST:event_button12ActionPerformed

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed

    }//GEN-LAST:event_button13ActionPerformed

    private void button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button14ActionPerformed

    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button15ActionPerformed

    }//GEN-LAST:event_button15ActionPerformed

    private void button16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button16ActionPerformed

    }//GEN-LAST:event_button16ActionPerformed

    private void button17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button17ActionPerformed

    private void button18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button18ActionPerformed

    }//GEN-LAST:event_button18ActionPerformed

    private void btnCambiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiar1ActionPerformed
    JPanel[] captchas = {panelMotocicletas2, panelSemaforo1, panelSemaforo2};
    JPanel currentPanel = panelMotocicletas1; // Panel inicial
    // Ocultar el panel actual
    currentPanel.setVisible(false);
    // Seleccionar un panel aleatorio diferente al actual
    Random random = new Random();
    JPanel selectedPanel;
    do {
        int randomIndex = random.nextInt(captchas.length);
        selectedPanel = captchas[randomIndex];
    } while (selectedPanel == currentPanel); 
    
    // Actualizar el panel actual y mostrar el nuevo panel seleccionado
    selectedPanel.setVisible(true);
    currentPanel = selectedPanel; // Actualizar el panel actual a este nuevo
    }//GEN-LAST:event_btnCambiar1ActionPerformed

    private void btnVerificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificar1ActionPerformed
// Identificar los botones correctos
        boolean[] correctSelections = {
            button12.isSelected(),
            button14.isSelected(),
            button17.isSelected(),
            button18.isSelected()
        };

        // Identificar todos los botones seleccionados
        JToggleButton[] allButtons = {
            button10, button11, button12, button13, button14, button15, button16, button17, button18
        };

        // Contar cuántos botones correctos están seleccionados
        int correctCount = 0;
        for (boolean isSelected : correctSelections) {
            if (isSelected) correctCount++;
        }

        // Verificar si exactamente 4 botones correctos están seleccionados y ningún otro
        if (correctCount == 4) {
            boolean onlyCorrectSelected = true;
            for (JToggleButton button : allButtons) {
                if (button.isSelected() && !(button == button12 || button == button14 || button == button17 || button == button18)) {
                    onlyCorrectSelected = false;
                    break;
                }
            }

            if (onlyCorrectSelected) {
                JOptionPane.showMessageDialog(null, "¡Felicidades, no eres un robot!");
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                if (frame != null) {
                    frame.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Vuelve a intentarlo");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vuelve a intentarlo");
        }
    }//GEN-LAST:event_btnVerificar1ActionPerformed

    private void button19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button19ActionPerformed
        
    }//GEN-LAST:event_button19ActionPerformed

    private void button20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button20MouseClicked

    }//GEN-LAST:event_button20MouseClicked

    private void button20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button20ActionPerformed

    }//GEN-LAST:event_button20ActionPerformed

    private void button21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button21ActionPerformed

    }//GEN-LAST:event_button21ActionPerformed

    private void button22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button22ActionPerformed

    }//GEN-LAST:event_button22ActionPerformed

    private void button23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button23ActionPerformed
       
    }//GEN-LAST:event_button23ActionPerformed

    private void button24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button24ActionPerformed

    }//GEN-LAST:event_button24ActionPerformed

    private void button25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button25ActionPerformed

    }//GEN-LAST:event_button25ActionPerformed

    private void button26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button26ActionPerformed

    private void button27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button27ActionPerformed

    }//GEN-LAST:event_button27ActionPerformed

    private void btnCambiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiar2ActionPerformed
    JPanel[] captchas = {panelMotocicletas2, panelMotocicletas1, panelSemaforo2};
    JPanel currentPanel = panelSemaforo1; // Panel inicial
    // Ocultar el panel actual
    currentPanel.setVisible(false);
    // Seleccionar un panel aleatorio diferente al actual
    Random random = new Random();
    JPanel selectedPanel;
    do {
        int randomIndex = random.nextInt(captchas.length);
        selectedPanel = captchas[randomIndex];
    } while (selectedPanel == currentPanel); 
    
    // Actualizar el panel actual y mostrar el nuevo panel seleccionado
    selectedPanel.setVisible(true);
    currentPanel = selectedPanel; // Actualizar el panel actual a este nuevo
    }//GEN-LAST:event_btnCambiar2ActionPerformed

    private void btnVerificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificar2ActionPerformed

        // Identificar los botones correctos
        boolean[] correctSelections = {
            button20.isSelected(),
            button21.isSelected(),
            button23.isSelected(),
            button26.isSelected()
        };

        // Identificar todos los botones seleccionados
        JToggleButton[] allButtons = {
            button19, button20, button21, button22, button23, button24, button25, button26, button27
        };

        // Contar cuántos botones correctos están seleccionados
        int correctCount = 0;
        for (boolean isSelected : correctSelections) {
            if (isSelected) correctCount++;
        }

        // Verificar si exactamente 4 botones correctos están seleccionados y ningún otro
        if (correctCount == 4) {
            boolean onlyCorrectSelected = true;
            for (JToggleButton button : allButtons) {
                if (button.isSelected() && !(button == button20 || button == button21 || button == button23 || button == button26)) {
                    onlyCorrectSelected = false;
                    break;
                }
            }

            if (onlyCorrectSelected) {
                JOptionPane.showMessageDialog(null, "¡Felicidades, no eres un robot!");
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                if (frame != null) {
                    frame.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Vuelve a intentarlo");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vuelve a intentarlo");
        }
    }//GEN-LAST:event_btnVerificar2ActionPerformed

    private void button37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button37ActionPerformed

    private void button38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button38MouseClicked

    }//GEN-LAST:event_button38MouseClicked

    private void button38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button38ActionPerformed

    }//GEN-LAST:event_button38ActionPerformed

    private void button39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button39ActionPerformed

    }//GEN-LAST:event_button39ActionPerformed

    private void button40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button40ActionPerformed

    }//GEN-LAST:event_button40ActionPerformed

    private void button41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button41ActionPerformed
       
    }//GEN-LAST:event_button41ActionPerformed

    private void button42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button42ActionPerformed

    }//GEN-LAST:event_button42ActionPerformed

    private void button43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button43ActionPerformed

    }//GEN-LAST:event_button43ActionPerformed

    private void button44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button44ActionPerformed

    private void button45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button45ActionPerformed

    }//GEN-LAST:event_button45ActionPerformed

    private void btnCambiar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiar4ActionPerformed
    JPanel[] captchas = {panelMotocicletas2, panelMotocicletas1, panelSemaforo2};
    JPanel currentPanel = panelSemaforo1; // Panel inicial
    // Ocultar el panel actual
    currentPanel.setVisible(false);
    // Seleccionar un panel aleatorio diferente al actual
    Random random = new Random();
    JPanel selectedPanel;
    do {
        int randomIndex = random.nextInt(captchas.length);
        selectedPanel = captchas[randomIndex];
    } while (selectedPanel == currentPanel); // Asegurarse de que sea diferente
    
    // Actualizar el panel actual y mostrar el nuevo panel seleccionado
    selectedPanel.setVisible(true);
    currentPanel = selectedPanel; // Actualizar el panel actual a este nuevo
    }//GEN-LAST:event_btnCambiar4ActionPerformed

    private void btnVerificar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificar4ActionPerformed

        // Identificar los botones correctos
        boolean[] correctSelections = {
            button38.isSelected(),
            button40.isSelected(),
            button43.isSelected(),
            button45.isSelected()
        };

        // Identificar todos los botones seleccionados
        JToggleButton[] allButtons = {
            button37, button38, button39, button40, button41, button42, button43, button44, button45
        };

        // Contar cuántos botones correctos están seleccionados
        int correctCount = 0;
        for (boolean isSelected : correctSelections) {
            if (isSelected) correctCount++;
        }

        // Verificar si exactamente 4 botones correctos están seleccionados y ningún otro
        if (correctCount == 4) {
            boolean onlyCorrectSelected = true;
            for (JToggleButton button : allButtons) {
                if (button.isSelected() && !(button == button38 || button == button40 || button == button43 || button == button45)) {
                    onlyCorrectSelected = false;
                    break;
                }
            }

            if (onlyCorrectSelected) {
                JOptionPane.showMessageDialog(null, "¡Felicidades, no eres un robot!");
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                if (frame != null) {
                    frame.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Vuelve a intentarlo");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vuelve a intentarlo");
        }
    }//GEN-LAST:event_btnVerificar4ActionPerformed

    private void chkVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVerificarActionPerformed
        if (chkVerificar.isSelected()) {
            // Oculta lblEstado1 y muestra lblEstado2
            lblVerify.setVisible(false);
            lblDone.setVisible(true);

            // Timer para esperar 2 segundos y luego abrir CaptchaMoto
            Timer timer = new Timer(2000, new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    panelInicio.setVisible(false);
                    panelMotocicletas1.setVisible(true);
                }
            });
            timer.setRepeats(false); // Ejecuta el Timer solo una vez
            timer.start();
        }
    }//GEN-LAST:event_chkVerificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnCambiar1;
    private javax.swing.JButton btnCambiar2;
    private javax.swing.JButton btnCambiar4;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JButton btnVerificar1;
    private javax.swing.JButton btnVerificar2;
    private javax.swing.JButton btnVerificar4;
    private javax.swing.JToggleButton button1;
    private javax.swing.JToggleButton button10;
    private javax.swing.JToggleButton button11;
    private javax.swing.JToggleButton button12;
    private javax.swing.JToggleButton button13;
    private javax.swing.JToggleButton button14;
    private javax.swing.JToggleButton button15;
    private javax.swing.JToggleButton button16;
    private javax.swing.JToggleButton button17;
    private javax.swing.JToggleButton button18;
    private javax.swing.JToggleButton button19;
    private javax.swing.JToggleButton button2;
    private javax.swing.JToggleButton button20;
    private javax.swing.JToggleButton button21;
    private javax.swing.JToggleButton button22;
    private javax.swing.JToggleButton button23;
    private javax.swing.JToggleButton button24;
    private javax.swing.JToggleButton button25;
    private javax.swing.JToggleButton button26;
    private javax.swing.JToggleButton button27;
    private javax.swing.JToggleButton button3;
    private javax.swing.JToggleButton button37;
    private javax.swing.JToggleButton button38;
    private javax.swing.JToggleButton button39;
    private javax.swing.JToggleButton button4;
    private javax.swing.JToggleButton button40;
    private javax.swing.JToggleButton button41;
    private javax.swing.JToggleButton button42;
    private javax.swing.JToggleButton button43;
    private javax.swing.JToggleButton button44;
    private javax.swing.JToggleButton button45;
    private javax.swing.JToggleButton button5;
    private javax.swing.JToggleButton button6;
    private javax.swing.JToggleButton button7;
    private javax.swing.JToggleButton button8;
    private javax.swing.JToggleButton button9;
    private javax.swing.JCheckBox chkVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lbl25;
    private javax.swing.JLabel lbl26;
    private javax.swing.JLabel lbl27;
    private javax.swing.JLabel lbl28;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl37;
    private javax.swing.JLabel lbl38;
    private javax.swing.JLabel lbl39;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl40;
    private javax.swing.JLabel lbl41;
    private javax.swing.JLabel lbl42;
    private javax.swing.JLabel lbl43;
    private javax.swing.JLabel lbl44;
    private javax.swing.JLabel lbl45;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblDone;
    private javax.swing.JLabel lblVerify;
    private javax.swing.JPanel pI;
    private javax.swing.JPanel panelInformacion;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelMotocicletas1;
    private javax.swing.JPanel panelMotocicletas2;
    private javax.swing.JPanel panelSemaforo1;
    private javax.swing.JPanel panelSemaforo2;
    // End of variables declaration//GEN-END:variables
}
